# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

stages:
- stage: Build
  displayName: Build stage
  jobs:
    - job: Build
      displayName: Build Job
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'package'

      - task: Maven@3
        displayName: Build Docker image
        inputs:
          mavenPomFile: 'pom.xml'
          goals: 'spring-boot:build-image'
          publishJUnitResults: false
          jdkVersionOption: '1.11'

      - task: Docker@2
        displayName: Push Docker image
        inputs:
          containerRegistry: 'acrdevopsbp'
          repository: ms-devops:0.0.1-SNAPSHOT'
          command: 'push'
          tags: 'latest'