# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

variables:
  imageRepo: ms-devops
  tag: '0.0.1-SNAPSHOT'

stages:
- stage: Build
  displayName: Build stage
  jobs:

    - job: Build
      displayName: Build Job
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: SonarCloudPrepare@1
        inputs:
          SonarCloud: 'sonarcloud'
          organization: 'jessyAviles'
          scannerMode: 'Other'
          extraProperties: |
            # Additional properties that will be passed to the scanner,
            # Put one key=value per line, example:
            # sonar.exclusions=**/*.bin
            sonar.projectKey=jessy_devops
            sonar.projectName=devops

      - task: Maven@3
        inputs:
          mavenPomFile: '$(Build.SourcesDirectory)/app/pom.xml'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          mavenVersionOption: 'Default'
          mavenOptions: '-Xmx512m'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: true
          isJacocoCoverageReportXML: true
          sqMavenPluginVersionChoice: 'latest'

      - task: SonarCloudAnalyze@1
        displayName: Run Code Analysis
        
      - task: SonarCloudPublish@1
        displayName: 'Publish Quality Gate Result'

      - task: Maven@3
        displayName: Build Docker image
        inputs:
          mavenPomFile: '$(Build.SourcesDirectory)/app/pom.xml'
          goals: 'spring-boot:build-image'
          publishJUnitResults: false
          jdkVersionOption: '1.11'

      - task: Docker@2
        displayName: Push Docker image
        inputs:
          containerRegistry: 'acrdevopsbp'
          repository: '$(imageRepo)'
          command: 'push'
          tags: '$(tag)'
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Pipeline.Workspace)/s/kubernetes'
          artifact: 'manifests'
          publishLocation: 'pipeline'
        
- stage: Deploy
  displayName: Deploy to Dev
  dependsOn: Build
  variables:
    acrsecret: k8sacrauth
    acrdevurl: 'acrdevops.azurecr.io'
    replicaNo: 3
  jobs:
  - deployment: Deploy
    displayName: Deploy to AKS
    environment: 'k8sdev.default'
    pool: 
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'manifests'
              targetPath: '$(Pipeline.Workspace)/manifests'
          - task: KubernetesManifest@0
            inputs:
              action: 'createSecret'
              namespace: 'default'
              secretType: 'dockerRegistry'
              secretName: '$(acrsecret)'
              dockerRegistryEndpoint: 'acrdevopsbp'
          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
              namespace: 'default'
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              containers: '$(acrdevurl)/$(imageRepo):$(tag)'
              imagePullSecrets: '$(acrsecret)'
